### ISSUE TITLE
GENERAL - Content Format: Incorrect content format as per sample content.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#23]
![22](https://cloud.githubusercontent.com/assets/18256652/14307284/64afff9e-fc00-11e5-827e-e51fc079e819.png)

**Comment by euveng** [comment]
If you look at the content editor here: http://cancercentre.stage.titanweb.com.au/wp-admin/post.php?post=3482&action=edit

..you will see that the output follows the content as a numbered list. I don't agree that we should force it to appear as letters when the input is clearly formatted as numbers.

**Comment by iteano** [comment]
This might be the auto format issue. What was the format of being copied should not be change when paste on the content editor. I guess the content editor was set to auto numbered list.

**Comment by euveng** [comment]
This is not a development issue, so I will flag this invalid.
