### ISSUE TITLE
OUR DOCTORS - Resolution testing: Image below moves from left to right at 863 view port size.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#26]
![25a](https://cloud.githubusercontent.com/assets/18256652/14309291/1488e5cc-fc0e-11e5-9864-ed8139ae626c.png)
![25b](https://cloud.githubusercontent.com/assets/18256652/14309293/15a24d86-fc0e-11e5-8a03-349ea9713667.png)

**Comment by euveng** [comment]
Fixed.
