### ISSUE TITLE
Top Header Menu - Resolution testing: Top header menu disappear and did not combine with the main Header menu as per project scope at 793 view port size.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#28]
![27](https://cloud.githubusercontent.com/assets/18256652/14309920/c1d09646-fc11-11e5-8923-13f8da6a27d6.png)

**Comment by euveng** [comment]
Unable to reproduce, please advise test parameters.

**Comment by iteano** [comment]
Closing this issue. Can't replicate this anymore in our end.
