### ISSUE TITLE
Admin: Social media are set in the backend but no social media links on the frontend as per design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#31]
![30](https://cloud.githubusercontent.com/assets/18256652/14338091/850271fe-fca6-11e5-829b-885b2e800bb8.png)
![01-the-homepage](https://cloud.githubusercontent.com/assets/18256652/14338094/8805a5ec-fca6-11e5-90f2-49999dd1e46f.png)

**Comment by euveng** [comment]
Social media is not included in design, will not fix.
