### ISSUE TITLE
Home Page: "READ MORE" button isn't customizable.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#35]
![34](https://cloud.githubusercontent.com/assets/18256652/14341458/7e0afa42-fcc4-11e5-91ae-3a4c6a28949d.png)

**Comment by euveng** [comment]
The 'Read More / Read Less' button is part of the arguments supplied to the jQuery function in the scripts.js file. It is not impossible to change the button text, but the benefit of doing this does not justify the significant effort taken to make this button customisable, so this won't be fixed.
