### ISSUE TITLE
GENERAL: The use of "titanweb" is still applied. Please change to "titandigital" as per standard.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#36]
![35](https://cloud.githubusercontent.com/assets/18256652/14341646/23e20cde-fcc6-11e5-811f-334ee6b60473.png)

**Comment by euveng** [comment]
Fixed.

**Comment by iteano** [comment]
Landing page still titanweb.

**Comment by euveng** [comment]
Fixed.

**Comment by iteano** [comment]
Verified fixed. Thanks.
