### ISSUE TITLE
GENERAL: Missing News/Blog page. As per knowledgebase implementation, News / Blog page must be implemented.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#37]
http://cancercentre.stage.titanweb.com.au/latest-news/

![36](https://cloud.githubusercontent.com/assets/18256652/14341833/a6228b0a-fcc7-11e5-9851-aacd39268929.png)

**Comment by euveng** [comment]
Latest News page created.
