### ISSUE TITLE
HOME: MEET OUR DOCTORS listing fonts for names seems to more bold than from design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#4]
![3](https://cloud.githubusercontent.com/assets/18256652/14272092/217b2114-fb32-11e5-8fd0-44eeed3ac151.png)

**Comment by euveng** [comment]
The thickness of this font-family in bold cannot be changed. However to improve readability, I introduced letter-spacing to create some space between the letters.
