### ISSUE TITLE
PAGINATION: Inconsitent pagination from design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#40]
As project scope, it is noted that "Note that bootstrap pagination will not have 'first and last page' links." We just want to clarify what if, let say for example, there where 20 post so it makes 4 pages, so the link for first and last page might be needed.
This is achievable, please refer to this project. http://linesent.stage.titanweb.com.au/news/

![39](https://cloud.githubusercontent.com/assets/18256652/14342815/36bb9948-fccf-11e5-9752-908bb7102f75.png)

**Comment by euveng** [comment]
Bootstrap will still output the first and last links as per http://wonderwalls.stage.titanweb.com.au/versatility/page/4/. 

In case this issue was missed - this is our new standard, it should not be an issue from now.
