### ISSUE TITLE
Header Menu: Please allow 2 level style menu.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#43]
![42](https://cloud.githubusercontent.com/assets/18256652/14515399/5af942b2-022c-11e6-80a2-33595ff36a8c.png)

**Comment by euveng** [comment]
Fixed.

**Comment by iteano** [comment]
Verified fixed. Thanks.

**Comment by iteano** [comment]
Please temporarily hide the submenus for now. This is just in case for client's future use. Thanks.
