### ISSUE TITLE
Top Header Menu - Please apply focus when mouse hover.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#46]
![45](https://cloud.githubusercontent.com/assets/18256652/14515835/ff03660a-022f-11e6-9904-93cad3110f95.png)

**Comment by euveng** [comment]
What colour should be used as the background colour for hover state?

**Comment by iteano** [comment]
Orange do fine. But could you please hide the separator once hover is active? Thanks.

**Comment by euveng** [comment]
Fixed.
