### ISSUE TITLE
OUR SERVICES - W3C: Error: An img element must have an alt attribute, except under certain conditions.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#49]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcancercentre.stage.titanweb.com.au%2Four-services%2F
![48](https://cloud.githubusercontent.com/assets/18256652/14517788/f61bb178-0243-11e6-89f6-d19f2999c654.png)

**Comment by euveng** [comment]
Fixed.
