### ISSUE TITLE
CLINICAL TRIALS - W3C: Error: An img element must have an alt attribute, except under certain conditions.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#50]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcancercentre.stage.titanweb.com.au%2Fclinical-trials%2F
![49](https://cloud.githubusercontent.com/assets/18256652/14517804/36fce018-0244-11e6-8280-7cd9cd5e1e75.png)

**Comment by euveng** [comment]
Fixed.
