### ISSUE TITLE
FOUC: Banner images loads on the page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#51]
![50](https://cloud.githubusercontent.com/assets/18256652/14518700/2bb5f41c-024c-11e6-9e0e-e0b1b8f52918.png)

**Comment by euveng** [comment]
Which browser is this occuring?

**Comment by euveng** [comment]
I've enqueued the slick carousel script to load in <head> instead of before </body>, please check if this still occurs.

**Comment by iteano** [comment]
Problem still occurs. I had tried it on firefox and chrome.

**Comment by euveng** [comment]
We are unable to reproduce this on our machines. Have discussed this with Jo, and the decision is that there is no issue, so will not fix.
