### ISSUE TITLE
Our Doctors/Our Team: Doctors names are clipped.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#52]
![51](https://cloud.githubusercontent.com/assets/18256652/14519469/c9f520f8-0251-11e6-80f1-0f2f20ae0600.png)

**Comment by euveng** [comment]
The original design allows for only one line in the title. To display 'Dr Ru-Wen Marianne Teh', the title needs to stretch over 2 lines. Since QA considers this as an issue, I have allowed for 2 lines.
