### ISSUE TITLE
REFERRER INFORMATION: Consultation Hours text set at the backend are not completely shown at the frontend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#53]
![52](https://cloud.githubusercontent.com/assets/18256652/14521690/2fe22608-025d-11e6-8adc-a6f4ec5d8d55.png)

**Comment by euveng** [comment]
This is needed to control the length of the output content. if not, the content will flow into the next line. Will not fix this.
