### ISSUE TITLE
OUR TEAM: Our team page single - RETURN TO OUR DOCTORS link will direct to OUR TEAM page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#6]
![6](https://cloud.githubusercontent.com/assets/18256652/14272798/7f787e64-fb38-11e5-86c9-3b9c11824363.png)

**Comment by euveng** [comment]
If you are on the single page of a doctor categorised as 'Our Team', clicking this link would bring you back to the category page.

How do you propose to change this? 

1. Allow this field to be customisable through an ACF?
2. Always direct this to the 'Our doctors' page?

**Comment by iteano** [comment]
Just change the link text to "RETURN TO OUR TEAM" since this page was generated from its parent page which is from our team page.

**Comment by euveng** [comment]
Fixed.

**Comment by iteano** [comment]
Verified fixed. Thanks.
